### PR TITLE
workaround for node bug joyent/node#8195

### PR DESCRIPTION
**Pull request by parisholley**
Pretty big bug that prevents this library from working in 0.12.x

### CODE REVIEW

**Comment by mhart** [comment]
This only occurs when in using this module with the `cluster` module in 0.12.x, correct?

**Comment by parisholley** [comment]
Yep

**Comment by mhart** [comment]
Is this still an issue? I believe it was fixed in node a while back: https://github.com/nodejs/node-v0.x-archive/pull/8642#issuecomment-70020806

**Comment by parisholley** [comment]
@mhart haven't look at it in a while, but I would assume so. those fixes weren't in place with the version i was using at the time

**Comment by mhart** [comment]
Ok, I'll close this, but if you see an issue feel free to open again

**Pull request closed without merging**
